import tkinter

window = tkinter.Tk()

tkinter.Label(window, text = "A1", bg = "red").grid(row = 0, column = 0)
tkinter.Label(window, text = "A2", bg = "blue").grid(row = 0, column = 1)
tkinter.Label(window, text = "A1", bg = "red").grid(row = 0, column = 2)
tkinter.Label(window, text = "A2", bg = "blue").grid(row = 0, column = 3)
tkinter.Label(window, text = "A1", bg = "red").grid(row = 0, column = 4)
tkinter.Label(window, text = "A2", bg = "blue").grid(row = 0, column = 5)
tkinter.Label(window, text = "A1", bg = "red").grid(row = 0, column = 6)
tkinter.Label(window, text = "A2", bg = "blue").grid(row = 0, column = 7)

tkinter.Label(window, text = "B1", bg = "blue").grid(row = 1, column = 0)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 1, column = 1)
tkinter.Label(window, text = "B1", bg = "blue").grid(row = 1, column = 2)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 1, column = 3)
tkinter.Label(window, text = "B1", bg = "blue").grid(row = 1, column = 4)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 1, column = 5)
tkinter.Label(window, text = "B1", bg = "blue").grid(row = 1, column = 6)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 1, column = 7)

tkinter.Label(window, text = "B1", bg = "red").grid(row = 2, column = 0)
tkinter.Label(window, text = "B2", bg = "blue").grid(row = 2, column = 1)
tkinter.Label(window, text = "B1", bg = "red").grid(row = 2, column = 2)
tkinter.Label(window, text = "B2", bg = "blue").grid(row = 2, column = 3)
tkinter.Label(window, text = "B1", bg = "red").grid(row = 2, column = 4)
tkinter.Label(window, text = "B2", bg = "blue").grid(row = 2, column = 5)
tkinter.Label(window, text = "B1", bg = "red").grid(row = 2, column = 6)
tkinter.Label(window, text = "B2", bg = "blue").grid(row = 2, column = 7)

tkinter.Label(window, text = "B1", bg = "blue").grid(row = 3, column = 0)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 3, column = 1)
tkinter.Label(window, text = "B1", bg = "blue").grid(row = 3, column = 2)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 3, column = 3)
tkinter.Label(window, text = "B1", bg = "blue").grid(row = 3, column = 4)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 3, column = 5)
tkinter.Label(window, text = "B1", bg = "blue").grid(row = 3, column = 6)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 3, column = 7)

tkinter.Label(window, text = "A1", bg = "red").grid(row = 4, column = 0)
tkinter.Label(window, text = "A2", bg = "blue").grid(row = 4, column = 1)
tkinter.Label(window, text = "A1", bg = "red").grid(row = 4, column = 2)
tkinter.Label(window, text = "A2", bg = "blue").grid(row = 4, column = 3)
tkinter.Label(window, text = "A1", bg = "red").grid(row = 4, column = 4)
tkinter.Label(window, text = "A2", bg = "blue").grid(row = 4, column = 5)
tkinter.Label(window, text = "A1", bg = "red").grid(row = 4, column = 6)
tkinter.Label(window, text = "A2", bg = "blue").grid(row = 4, column = 7)

tkinter.Label(window, text = "B1", bg = "blue").grid(row = 5, column = 0)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 5, column = 1)
tkinter.Label(window, text = "B1", bg = "blue").grid(row = 5, column = 2)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 5, column = 3)
tkinter.Label(window, text = "B1", bg = "blue").grid(row = 5, column = 4)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 5, column = 5)
tkinter.Label(window, text = "B1", bg = "blue").grid(row = 5, column = 6)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 5, column = 7)

tkinter.Label(window, text = "B1", bg = "red").grid(row = 6, column = 0)
tkinter.Label(window, text = "B2", bg = "blue").grid(row = 6, column = 1)
tkinter.Label(window, text = "B1", bg = "red").grid(row = 6, column = 2)
tkinter.Label(window, text = "B2", bg = "blue").grid(row = 6, column = 3)
tkinter.Label(window, text = "B1", bg = "red").grid(row = 6, column = 4)
tkinter.Label(window, text = "B2", bg = "blue").grid(row = 6, column = 5)
tkinter.Label(window, text = "B1", bg = "red").grid(row = 6, column = 6)
tkinter.Label(window, text = "B2", bg = "blue").grid(row = 6, column = 7)

tkinter.Label(window, text = "B1", bg = "blue").grid(row = 7, column = 0)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 7, column = 1)
tkinter.Label(window, text = "B1", bg = "blue").grid(row = 7, column = 2)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 7, column = 3)
tkinter.Label(window, text = "B1", bg = "blue").grid(row = 7, column = 4)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 7, column = 5)
tkinter.Label(window, text = "B1", bg = "blue").grid(row = 7, column = 6)
tkinter.Label(window, text = "B2", bg = "red").grid(row = 7, column = 7)

resizable(True, True)

window.mainloop()